### PR TITLE
Some updates from fedora packaging

### PR DESCRIPTION
**Pull request by leamas**
As requested in email. I note that some missing in the 1.44 archive actually are in place here on github.

### CODE REVIEW

**Comment by leamas** [comment]
Indeed. I didn't check when the patch applied. Know that my patches are based on the 1.44 zip archive, not on this exact source.

**Comment by leamas** [comment]
BTW, no-one but you can use the build script since it requires your signing key.

**Comment by stewartoallen** [comment]
i'll have to fix that

**Comment by leamas** [comment]
FYI: I have been forced to remove the osbaldeston files, the bmp support. They lack any license information, and the author seems completely off the net since many years.

I have also removed some Mac-specific code. This was a pretty clean patch.

**Pull request merged**
